//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge_student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_options
    {
        public int Number_answer_option { get; set; }
        public string Answer_option { get; set; }
        public int Number_question { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
