//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge_student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option_answers
    {
        public int Number_option_answer { get; set; }
        public int Number_quesion { get; set; }
        public string Option_answer { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
