//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge_student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Number_question { get; set; }
        public string Question { get; set; }
        public int Number_theme { get; set; }
        public string Answers { get; set; }
        public int Points { get; set; }
        public int Number_test { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Themes Themes { get; set; }
    }
}
