//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knowledge_student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_for_tests
    {
        public int Number_test { get; set; }
        public string Name_test { get; set; }
        public string Name_discipline { get; set; }
        public string Name_theme { get; set; }
        public int Max_point { get; set; }
        public string Name_teacher { get; set; }
    }
}
